version: "3.3"
services:
  artipie:
    image: artipie/artipie:latest
    container_name: artipie
    restart: unless-stopped
    volumes:
      - /home/artipie/artipie.yml:/etc/artipie/artipie.yml
      - /home/artipie/repo:/var/artipie/repo
      - /home/artipie/security:/var/artipie/security
    networks:
      - artipie-net
    ports:
      - "3012:8080"
      - "3013:8086"
  front:
    image: artipie/front:v0.2.3
    container_name: front
    restart: unless-stopped
    networks:
      - artipie-net
    environment:
      - ARTIPIE_REST=http://artipie:8086
    ports:
      - "3014:8080"

networks:
  artipie-net:
    driver: bridge