version: "3"
networks:
  loki:
services:
  loki:
    image: grafana/loki:2.4.0
    container_name: loki
    volumes:
      - /home/grafana/loki:/etc/loki
    ports:
      - "3008:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
  promtail:
    image: grafana/promtail:2.4.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /home/grafana/promtail:/etc/promtail
    ports:
      - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1006"
    volumes:
    - /home/grafana/grafana:/var/lib/grafana
    ports:
      - "3009:3000"
    restart: unless-stopped
    networks:
      - loki
