version: "3.1"
services:

  db:
    image: postgres:11-alpine
    container_name: wiki-db
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - /home/wiki/db-data:/var/lib/postgresql/data
    networks:
      - wikinet
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  wiki:
    image: requarks/wiki:2.5
    container_name: wiki
    depends_on:
      - db
    environment:
      PORT: 3000 # DO NOT CHANGE THIS LINE! Use ports below to specify listening port.
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    networks:
      - wikinet
    ports:
      - "3001:3000" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  wikinet:

volumes:
  db-data:
